name: onboarding_app
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  intro_views_flutter: ^2.8.0
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/recycle.png
    - assets/reduce.png
    - assets/reuse.png
  fonts:
    - family: BreeSerif
      fonts:
        - asset: assets/BreeSerif.ttf
